#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

# ANSI color codes for formatting
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check the exit status of the previous command
if [ $? -ne 0 ]; then
  echo "${RED}Linting failed. Aborting commit.${NC}"
  exit 1
fi